name: "beta.gouv API scan"
description: "Fetch SE info from the beta.gouv.fr public API"

inputs:
  id:
    description: "The unique identifier of the SE on the beta.gouv website."
    required: true
  api_url:
    description: "The betagouv website api url for SE."
    default: "https://beta.gouv.fr/api/v2.4/startups.json"
    required: false
  output:
    description: "Path to output file. defaults to betagouv.json."
    default: "betagouv.json"
    required: false
outputs:
  stats_url:
    description: "The stat page URL if any"
    value: ${{ steps.betagouv.outputs.stats_url }}
  budget_url:
    description: "The budget page URL if any"
    value: ${{ steps.betagouv.outputs.budget_url }}
  github_repository:
    description: "The Github repository"
    value: ${{ steps.betagouv.outputs.github_repository }}

runs:
  using: "composite"
  steps:
    - name: Scan betagouv api
      shell: bash
      id: betagouv
      run: |
        if [ ! -x "$(command -v jq)" ]; then sudo apt-get install -y jq; fi
        if [ ! -x "$(command -v wget)" ]; then sudo apt-get install -y wget; fi
        wget -O - ${{ inputs.api_url }} | jq '.data[] | select(.id == "${{ inputs.id }}")' > ${{ inputs.output }}

        stats_url=$( cat ${{ inputs.output }} | jq -r ".attributes.stats_url" )
        budget_url=$( cat ${{ inputs.output }} | jq -r ".attributes.budget_url" )
        github_repository=$( cat ${{ inputs.output }} | jq -r ".attributes.repository" )
        echo "::set-output name=stats_url::$(echo $stats_url)"
        echo "::set-output name=budget_url::$(echo $budget_url)"
        echo "::set-output name=github_repository::$(echo $github_repository)"

        echo "created in ${{ inputs.output }}"
        echo "stats_url: $stats_url"
        echo "budget_url: $budget_url"
        echo "github_repository: $github_repository"
