on:
  push:
    branches: ["*"]

name: Tests betagouv API action
jobs:
  tests-betagouv:
    runs-on: ubuntu-latest
    name: betagouv api action
    steps:
      - uses: actions/checkout@v2
      - name: Run beta.gouv API fetcher
        id: betagouv
        uses: ./
        with:
          id: mon-entreprise
          output: betagouv.json
      - shell: bash
        run: |
          python -m json.tool < betagouv.json
          cat betagouv.json
          stats_url="${{ steps.betagouv.outputs.stats_url }}"
          budget_url="${{ steps.betagouv.outputs.budget_url }}"
          se_current_phase="${{ steps.betagouv.outputs.se_current_phase }}"
          echo "stats_url: $stats_url"
          echo "budget_url: $budget_url"
          echo "se_current_phase: $se_current_phase"
          [[ "$stats_url" != "https://mon-entreprise.urssaf.fr/stats" ]] && exit 1
          [[ "$budget_url" != "https://mon-entreprise.urssaf.fr/budget" ]] && exit 1
          [[ "$se_current_phase" != "success" ]] && exit 1
          exit 0
