on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

name: Tests betagouv API action
jobs:
  tests-betagouv:
    runs-on: ubuntu-latest
    name: betagouv api action
    steps:
      - uses: actions/checkout@v2
      - name: Run beta.gouv API fetcher
        uses: ./
        with:
          id: signaux-faibles
          output: betagouv.json
      - shell: bash
        run: |
          python -m json.tool < betagouv.json
          cat betagouv.json
